# Site settings
title: "CV y Portafolio Sergio Bourguet"
author: "Sergio Bourguet"
description: "CV y Portafolio de Sergio Bourguet Caldarella"
keywords: "Diseño editorial, Diseño gráfico, Diseño, Comunicación, Comunicación visual"
biography: "Semblanza con links"
colophon: "© MMXIII — MMXVI Design by Hugo Sereno Ferreira.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "https://ovisnigra.github.io/papyrus-theme/"

twitter_username: ovisnigra
github_username: ovisnigra
linkedin_username: 
facebook_username: 
google-analytics: 

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
